spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/store?currentSchema=store
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true